[package]
name = "todouble_derive"
version = "0.1.0"
edition = "2024"

[dependencies]
darling = "0.20.10"
deluxe = "0.5.0"
proc-macro2 = "1.0.86"
quote = "1.0.36"
syn = { version = "2.0.72", features = ["full"] }

[lib]
proc-macro = true
