[package]
name = "required_proc"
version = "0.1.0"
edition = "2024"

[dependencies]
darling = "0.20.10"
proc-macro2 = "1.0.86"
prost = "0.14.3"
quote = "1.0.36"
syn = { version = "2.0.72", features = ["full"] }

[lib]
proc-macro = true
